---
- name: Include OS family specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"

- import_tasks: uchiwa_pre.yml
- import_tasks: uchiwa_install.yml

- block: # Config Uchiwa
  - import_tasks: uchiwa_search_config.yml
  - import_tasks: uchiwa_post.yml
  tags:
    - uchiwa-config